version: "3.8"
services:
  main:
    build: .
    container_name: Njombers
    restart: unless-stopped
    volumes:
      - state-data:/app/state/
    environment:
      - CHANNEL_ID
      - CLIENT_ID
      - CLIENT_SECRET
      - TOKEN
      - UNIQUE_USERS
      - DEBUG_CHANNEL_ID
      - ADMIN_IDS

volumes:
  state-data:
